### ISSUE TITLE
New Commands

### ISSUE THREAD

**Issue by aneisch** [aamarioneta/IRDenon#4]
Good day, can you share where you got these IR commands from? Did you sniff them? I'd like to add additional functionality but I have been unable to locate additional commands.

**Comment by aamarioneta** [comment]
Hi. Yes i sniffed them using a ir receiver. See here: https://github.com/crankyoldgit/IRremoteESP8266/wiki#ir-receiving
i think i used the IRrecvDemo.ino to just print out the values.

-------- Original Message --------

**Comment by aneisch** [comment]
Neat, thank you! Unfortunately I found my receiver in a dumpster and don't have the remote 😂

I'll see if I can convert some codes I found online.

**Comment by aneisch** [comment]
FWIW I have had success using codes from [here](http://assets.denon.com/documentmaster/us/denon%20master%20ir%20hex.xls) with my ESPHome config after conversion with: [convert_pronto_codes.py](https://raw.githubusercontent.com/aneisch/home-assistant-config/master/extras/scripts/convert_pronto_codes.py).

**Comment by nbonamy** [comment]
Hello,

can you give some insights on how you converted codes from the Excel file with the script?

Trying to convert some codes but can never find the same result? What does DENON 223C means for instance?

Thanks!

**Comment by aneisch** [comment]
It's been a minute but I believe I used this:
https://github.com/aneisch/home-assistant-config/blob/master/extras/scripts/convert_pronto_codes.py

Just grab the pronto string and paste when running that script. You might have to try different codes if you find varied ones.
